model:
  target: vqgan.models.vqgan.VQModel
  params:
    codebook:
      dim: 256
      n_embeds: 1024
    encoder_decoder:
      dimension: 2 # would be 1 for audio waveform ;)
      resolution: 128
      in_channels: 3 # RGB
      out_channels: 3 # RGB

      channels: 128 # first convolution out dim
      channel_multiplier: [1, 1, 2, 1] # by how much to multiply the channel for each successive layer
      z_channels: 256 # the last layer
      num_res_blocks: 2 # number of residual blocks per layer
      resolution_attention: []

loss:
  codebook_loss: 1.0
  pixel_loss: 1.0
  perceptual_loss: 0.0

train:
  lr: 4.5e-6
  total_steps: 15000
  save_every: 1000
  sample_every: 100

data:
  dir: /home/lleonard/Documents/datasets/img_align_celeba/
  batch_size: 26
